kind: Service
apiVersion: v1
metadata:
  name: code-server
spec:
  type: LoadBalancer
  selector:
    app: code-server
  ports:
  - protocol: TCP
    port: 8080


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server-deployment
  labels:
    app: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
      track: stable
  template:
    metadata:
      labels:
        app: code-server
        track: stable
    spec:
      containers:
      - name: code-server
        image: skyline27042012/code-server
        
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 150
          timeoutSeconds: 100
          periodSeconds: 100
        resources:
          requests:
            cpu: 2
            memory: "4Gi"
